# Generated by Django 4.2.3 on 2024-01-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0012_user_is_encarregado_user_is_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_permissions_users', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
