# Generated by Django 5.0.4 on 2024-04-23 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encarregado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='encarregado_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.encarregado'),
        ),
        migrations.AddField(
            model_name='horario',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
        migrations.AddField(
            model_name='informacoesacademicas',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_academicas', to='app.aluno'),
        ),
        migrations.AddField(
            model_name='mensagemsms',
            name='encarregado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='app.encarregado'),
        ),
        migrations.AddField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aluno'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aluno'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='encarregado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.encarregado'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aluno'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aula'),
        ),
        migrations.AddField(
            model_name='professor',
            name='conteudos_educacionais',
            field=models.ManyToManyField(blank=True, related_name='conteudo', to='app.conteudoeducacional'),
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplinas_associadas',
            field=models.ManyToManyField(to='app.disciplina'),
        ),
        migrations.AddField(
            model_name='professor',
            name='horarios',
            field=models.ManyToManyField(blank=True, related_name='horarios_professor', to='app.horario'),
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagemsms',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='app.professor'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.professor', verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='evento',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
        ),
        migrations.AddField(
            model_name='disciplinaselecionada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
        ),
        migrations.AddField(
            model_name='conteudoeducacional',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
        ),
        migrations.AddField(
            model_name='professordisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
        migrations.AddField(
            model_name='professordisciplina',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
        ),
        migrations.AddField(
            model_name='nota',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professordisciplina'),
        ),
        migrations.AddField(
            model_name='propina',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.aluno'),
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='turmas', to='app.aluno'),
        ),
        migrations.AddField(
            model_name='professor',
            name='turmas_associadas',
            field=models.ManyToManyField(blank=True, to='app.turma'),
        ),
        migrations.AddField(
            model_name='horario',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='estatisticaturma',
            name='turma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.turma'),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
    ]
