# Generated by Django 4.2.3 on 2024-02-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemsms',
            name='encarregado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='app.encarregado'),
        ),
        migrations.AlterField(
            model_name='mensagemsms',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='app.professor'),
        ),
    ]
