# Generated by Django 4.2.3 on 2024-02-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mensagemsms_encarregado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemsms',
            name='mensagem_respondida',
            field=models.BooleanField(default=False),
        ),
    ]
