# Generated by Django 4.2.3 on 2024-02-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mensagemsms_mensagem_respondida'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemsms',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
