# Generated by Django 4.2.3 on 2024-02-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mensagemsms_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemsms',
            name='resposta_professor',
            field=models.BooleanField(default=False),
        ),
    ]
