# Generated by Django 4.2.3 on 2024-02-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mensagemsms_resposta_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemsms',
            name='resposta_professor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
