# Generated by Django 4.2.3 on 2024-02-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_mensagemsms_resposta_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='foto',
            new_name='imagem',
        ),
    ]
