# Generated by Django 4.2.3 on 2024-02-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_turmadisciplina_estatisticaturma'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatisticaturma',
            name='media_notas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estatisticaturma',
            name='total_alunos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
