# Generated by Django 4.2.3 on 2024-03-11 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_estatisticaturma_media_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professordisciplina'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo_prova',
            field=models.CharField(choices=[('Prova', 'Prova'), ('Trabalho', 'Trabalho'), ('Projeto', 'Projeto')], max_length=100),
        ),
    ]
