# Generated by Django 5.0.3 on 2024-04-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_avaliacao_disciplina_alter_nota_tipo_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='profissao_encarregado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
