# Generated by Django 5.0.3 on 2024-04-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_comunicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='enviar_para_todos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='encarregado_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.encarregado'),
        ),
    ]
