# Generated by Django 5.0.3 on 2024-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_comunicado_enviar_para_todos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesAcademicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desempenho_academico', models.TextField(verbose_name='Desempenho Acadêmico')),
                ('frequencia_escolar', models.CharField(max_length=100, verbose_name='Frequência Escolar')),
                ('horario_aulas', models.CharField(max_length=100, verbose_name='Horário das Aulas')),
            ],
        ),
    ]
