# Generated by Django 5.0.3 on 2024-04-09 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_informacoesacademicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesacademicas',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_academicas', to='app.aluno'),
            preserve_default=False,
        ),
    ]
