# Generated by Django 5.0.3 on 2024-04-11 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_comportamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='hora_fim',
            new_name='hora_termino',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='aulas',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='professor',
        ),
        migrations.AddField(
            model_name='horario',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='sala_aula',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
