# Generated by Django 5.0.3 on 2024-04-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_hora_fim_horario_hora_termino_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='hora_fim',
            new_name='fim',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='hora_inicio',
            new_name='inicio',
        ),
    ]
