# Generated by Django 5.0.3 on 2024-04-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_hora_fim_aula_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professordisciplina',
            name='lecionando',
            field=models.BooleanField(default=False),
        ),
    ]
