# Generated by Django 5.0.3 on 2024-04-11 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_professordisciplina_lecionando'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
            preserve_default=False,
        ),
    ]
