# Generated by Django 5.0.3 on 2024-04-11 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_disciplina_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
            preserve_default=False,
        ),
    ]
