# Generated by Django 5.0.3 on 2024-04-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_aula_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='professor',
        ),
    ]
