# Generated by Django 5.0.3 on 2024-04-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='outro_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo',
            field=models.CharField(choices=[('Folha de Prova', 'Folha de Prova'), ('Passe', 'Passe'), ('Propina', 'Propina'), ('Dívida', 'Dívida'), ('Material Escolar', 'Material Escolar'), ('Atividade Extracurricular', 'Atividade Extracurricular'), ('Uniforme Escolar', 'Uniforme Escolar'), ('Taxa de Matrícula', 'Taxa de Matrícula'), ('Lanche', 'Lanche'), ('Excursão', 'Excursão')], max_length=100),
        ),
    ]
