# Generated by Django 5.0.3 on 2024-04-17 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_pagamento_outro_tipo_alter_pagamento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.aluno'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Data e Hora de Início')),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Término')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
                ('cor', models.CharField(blank=True, max_length=6, verbose_name='Cor')),
                ('tipo_evento', models.CharField(max_length=50, verbose_name='Tipo de Evento')),
                ('arquivo', models.FileField(blank=True, upload_to='calendarios/', verbose_name='Arquivo')),
                ('recorrencia', models.CharField(blank=True, max_length=20, verbose_name='Recorrência')),
                ('link_externo', models.URLField(blank=True, verbose_name='Link Externo')),
                ('visibilidade', models.CharField(default='Público', max_length=10, verbose_name='Visibilidade')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.professor', verbose_name='Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma')),
            ],
        ),
    ]
