# Generated by Django 5.0.3 on 2024-04-17 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_pagamento_aluno_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
