# Generated by Django 5.0.3 on 2024-04-18 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_eventos_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
        ),
    ]
