# Generated by Django 5.0.3 on 2024-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_aluno_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='trimestre',
            field=models.IntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre')]),
        ),
    ]
