# Generated by Django 5.0.3 on 2024-04-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_avaliacao_trimestre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.professordisciplina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('Prova', 'Prova'), ('Trabalho', 'Trabalho'), ('Projeto', 'Projeto'), ('Participação', 'Participação'), ('Tarefa', 'Tarefa'), ('Apresentação', 'Apresentação'), ('Exercício', 'Exercício'), ('Avaliação Oral', 'Avaliação Oral'), ('Outro', 'Outro')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='trimestre',
            field=models.IntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre')], default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='nota',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='tipo_prova',
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
