# Generated by Django 5.0.4 on 2024-04-28 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_nota_unique_together_nota_aluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='turma',
        ),
        migrations.AlterField(
            model_name='mensagemsms',
            name='encarregado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='app.encarregado'),
        ),
        migrations.AlterField(
            model_name='mensagemsms',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='app.professor'),
        ),
    ]
