# Generated by Django 5.0.4 on 2024-04-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_conteudo_story_descricao_remove_story_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
