# Generated by Django 5.0.4 on 2024-04-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_professor_horarios_horario_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='Tema',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='objectivo',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
