# Generated by Django 5.0.4 on 2024-05-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_aula_tema_aula_objectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
