# Generated by Django 5.0.3 on 2024-05-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_aula_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='presente',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('T', 'Atrasado'), ('J', 'Justificado')], default='A', max_length=1),
        ),
    ]
