# Generated by Django 5.0.3 on 2024-05-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_presenca_nota_alter_presenca_presente'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
