# Generated by Django 5.0.3 on 2024-05-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_presenca_justificativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propina',
            name='tipo_pagamento',
        ),
        migrations.AddField(
            model_name='propina',
            name='divida',
            field=models.DecimalField(decimal_places=2, default=14000.0, max_digits=10),
        ),
    ]
