# Generated by Django 5.0.3 on 2024-05-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_propina_tipo_pagamento_propina_divida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propina',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
