# Generated by Django 5.0.3 on 2024-05-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_pagamento_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='horarios',
            field=models.ManyToManyField(blank=True, related_name='horarios_professor', to='app.horario'),
        ),
    ]
